"""add faq and system prompt to project

Revision ID: 9bcdbf0db15d
Revises: d4e1f8c3a2b9
Create Date: 2026-05-08 15:32:33.346827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcdbf0db15d'
down_revision: Union[str, Sequence[str], None] = 'd4e1f8c3a2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
